### ISSUE TITLE
New multimodal cell segmentation kit

### ISSUE THREAD

**Issue by NKalavros** [maximilian-heeg/xenium-segmentation#4]
Hi Max,

Gorgeous work for both this and MERSCOPE. Since 10X rolled out the CellSeg kit, I was wondering if updating this is in your short term goals. I have made some slight changes in a version I put together which I am trying out, happy to put in a pull request.

Basically the only thing I'm currently changing is the NuclearSegmentation notebook to use the internal RNA stain and DAPI and the cyto3 model. Rest are just renaming the word nucleus to cell in all places I could.

Let me know what you think.

**Comment by maximilian-heeg** [comment]
Hi,

I don't have any plans to update this (yet). We have not done any new runs with the new segmentation kit (and firmware version 2) as we are currently waiting for some maintenance of the machine. 

I think your suggestion makes sense. If you already have a working version, I would be happy about a pull request. Alternatively (and depending on how well the 10x segmentation is working) another solution could be to use the 10x segmentation as the prior segmentation for Baysor (without running cellpose again). I did not want to do this is the past because I felt like the nuclear expansion approach was not ideal, but it might work with the new kit.

Happy to hear your thoughts.
Max
